### ISSUE TITLE
Unable to delete/edit items using the UI

### ISSUE THREAD

**Issue by eli-oat** [nlware/vue-crud-ui#15]
I've actually tried both vue-crud-ui, and php-crud-ui. I can't get either to edit or delete items. Both will add new ones, though.

Any insight into what is causing this is greatly appreciated. 

Thanks!

**Comment by mvdriel** [comment]
Hi @eli-oat 

Thanks you for creating this issue.

Probably your webserver doesn't allow the http verbs delete and put. You can verify this using Postman before trying the ui any further.

**Comment by eli-oat** [comment]
Thanks @mvdriel! 

That solved it.

**Comment by elbasan** [comment]
I'm actually having the same problem, its not showing anything from the database in XAMPP

postman works fine thou
