### ISSUE TITLE
vue.js:1453 TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by derChristoph** [nlware/vue-crud-ui#20]
Great Tool! but i cant List my data, i think the problem is near by:

`            <td v-if="references[key] !== false">
              <router-link v-bind:to="{name: 'View', params: {subject: references[key][0], id: value}}">{{ referenceText(references[key][0], references[key][1], value) }}</router-link>
            </td>`

But i have no glue about vue, can someone help?

here is a install: https://wawi.carat.de/fehlerberichte/v1/ui.html#/test

**Comment by levhita** [comment]
Similar, same line for VueJS
`TypeError: references[key] is undefined`

**Comment by mvdriel** [comment]
Thank you for reporting this. I'll look into this.

**Comment by mvdriel** [comment]
This should be resolved in the latest version/master. Feedback is appreciated. Thank you.

**Comment by thipages** [comment]
Hi, got the same error some time ago. Resolved now. Thanks
